# Form implementation generated from reading ui file 'ui/new_record_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_record_rabies(object):
    def setupUi(self, record_rabies):
        record_rabies.setObjectName("record_rabies")
        record_rabies.resize(605, 171)
        self.pushButton_cancel_add = QtWidgets.QPushButton(parent=record_rabies)
        self.pushButton_cancel_add.setGeometry(QtCore.QRect(200, 130, 75, 24))
        self.pushButton_cancel_add.setObjectName("pushButton_cancel_add")
        self.pushButton_save_add = QtWidgets.QPushButton(parent=record_rabies)
        self.pushButton_save_add.setGeometry(QtCore.QRect(100, 130, 75, 24))
        self.pushButton_save_add.setObjectName("pushButton_save_add")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=record_rabies)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 581, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_rabies_add = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        self.tableWidget_rabies_add.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableWidget_rabies_add.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tableWidget_rabies_add.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableWidget_rabies_add.setObjectName("tableWidget_rabies_add")
        self.tableWidget_rabies_add.setColumnCount(5)
        self.tableWidget_rabies_add.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies_add.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies_add.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies_add.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies_add.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies_add.setHorizontalHeaderItem(4, item)
        self.tableWidget_rabies_add.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget_rabies_add)
        self.error_label = QtWidgets.QLabel(parent=record_rabies)
        self.error_label.setGeometry(QtCore.QRect(30, 100, 331, 16))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")

        self.retranslateUi(record_rabies)
        QtCore.QMetaObject.connectSlotsByName(record_rabies)

    def retranslateUi(self, record_rabies):
        _translate = QtCore.QCoreApplication.translate
        record_rabies.setWindowTitle(_translate("record_rabies", "Form"))
        self.pushButton_cancel_add.setText(_translate("record_rabies", "Отменить"))
        self.pushButton_save_add.setText(_translate("record_rabies", "Сохранить"))
        self.tableWidget_rabies_add.setSortingEnabled(False)
        item = self.tableWidget_rabies_add.horizontalHeaderItem(0)
        item.setText(_translate("record_rabies", "Препарат"))
        item = self.tableWidget_rabies_add.horizontalHeaderItem(1)
        item.setText(_translate("record_rabies", "Дата вакцинации"))
        item = self.tableWidget_rabies_add.horizontalHeaderItem(2)
        item.setText(_translate("record_rabies", "Действительно до"))
        item = self.tableWidget_rabies_add.horizontalHeaderItem(3)
        item.setText(_translate("record_rabies", "Номер серии"))
        item = self.tableWidget_rabies_add.horizontalHeaderItem(4)
        item.setText(_translate("record_rabies", "Вет.врач (клиника)"))
