# Form implementation generated from reading ui file 'ui\new_record_ectoparasites.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_record_ectoparasites(object):
    def setupUi(self, record_ectoparasites):
        record_ectoparasites.setObjectName("record_ectoparasites")
        record_ectoparasites.resize(477, 151)
        self.pushButton_save_add = QtWidgets.QPushButton(parent=record_ectoparasites)
        self.pushButton_save_add.setGeometry(QtCore.QRect(100, 120, 75, 24))
        self.pushButton_save_add.setObjectName("pushButton_save_add")
        self.pushButton_cancel_add = QtWidgets.QPushButton(parent=record_ectoparasites)
        self.pushButton_cancel_add.setGeometry(QtCore.QRect(200, 120, 75, 24))
        self.pushButton_cancel_add.setObjectName("pushButton_cancel_add")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=record_ectoparasites)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_ectoparasites_add = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        self.tableWidget_ectoparasites_add.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableWidget_ectoparasites_add.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tableWidget_ectoparasites_add.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableWidget_ectoparasites_add.setObjectName("tableWidget_ectoparasites_add")
        self.tableWidget_ectoparasites_add.setColumnCount(4)
        self.tableWidget_ectoparasites_add.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ectoparasites_add.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ectoparasites_add.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ectoparasites_add.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ectoparasites_add.setHorizontalHeaderItem(3, item)
        self.tableWidget_ectoparasites_add.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget_ectoparasites_add)
        self.error_label = QtWidgets.QLabel(parent=record_ectoparasites)
        self.error_label.setGeometry(QtCore.QRect(30, 100, 331, 16))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")

        self.retranslateUi(record_ectoparasites)
        QtCore.QMetaObject.connectSlotsByName(record_ectoparasites)

    def retranslateUi(self, record_ectoparasites):
        _translate = QtCore.QCoreApplication.translate
        record_ectoparasites.setWindowTitle(_translate("record_ectoparasites", "Form"))
        self.pushButton_save_add.setText(_translate("record_ectoparasites", "Сохранить"))
        self.pushButton_cancel_add.setText(_translate("record_ectoparasites", "Отменить"))
        self.tableWidget_ectoparasites_add.setSortingEnabled(False)
        item = self.tableWidget_ectoparasites_add.horizontalHeaderItem(0)
        item.setText(_translate("record_ectoparasites", "Препарат"))
        item = self.tableWidget_ectoparasites_add.horizontalHeaderItem(1)
        item.setText(_translate("record_ectoparasites", "Дата вакцинации"))
        item = self.tableWidget_ectoparasites_add.horizontalHeaderItem(2)
        item.setText(_translate("record_ectoparasites", "Действительно до"))
        item = self.tableWidget_ectoparasites_add.horizontalHeaderItem(3)
        item.setText(_translate("record_ectoparasites", "Вет.врач (клиника)"))
