# Form implementation generated from reading ui file 'ui/rabies_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_rabies_table_window(object):
    def setupUi(self, rabies_table_window):
        rabies_table_window.setObjectName("rabies_table_window")
        rabies_table_window.resize(603, 403)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=rabies_table_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 571, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_rabies = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        self.tableWidget_rabies.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableWidget_rabies.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tableWidget_rabies.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableWidget_rabies.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget_rabies.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableWidget_rabies.setObjectName("tableWidget_rabies")
        self.tableWidget_rabies.setColumnCount(6)
        self.tableWidget_rabies.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_rabies.setHorizontalHeaderItem(5, item)
        self.tableWidget_rabies.horizontalHeader().setVisible(True)
        self.tableWidget_rabies.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_rabies.horizontalHeader().setHighlightSections(True)
        self.tableWidget_rabies.verticalHeader().setVisible(True)
        self.tableWidget_rabies.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tableWidget_rabies)
        self.pushButton_exit = QtWidgets.QPushButton(parent=rabies_table_window)
        self.pushButton_exit.setGeometry(QtCore.QRect(100, 370, 75, 24))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.name_table = QtWidgets.QLabel(parent=rabies_table_window)
        self.name_table.setGeometry(QtCore.QRect(110, 10, 201, 16))
        self.name_table.setObjectName("name_table")
        self.pushButton_add = QtWidgets.QPushButton(parent=rabies_table_window)
        self.pushButton_add.setGeometry(QtCore.QRect(20, 370, 75, 24))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_delete = QtWidgets.QPushButton(parent=rabies_table_window)
        self.pushButton_delete.setGeometry(QtCore.QRect(190, 370, 75, 24))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.error_label = QtWidgets.QLabel(parent=rabies_table_window)
        self.error_label.setGeometry(QtCore.QRect(20, 350, 441, 16))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")

        self.retranslateUi(rabies_table_window)
        QtCore.QMetaObject.connectSlotsByName(rabies_table_window)

    def retranslateUi(self, rabies_table_window):
        _translate = QtCore.QCoreApplication.translate
        rabies_table_window.setWindowTitle(_translate("rabies_table_window", "Form"))
        self.tableWidget_rabies.setSortingEnabled(True)
        item = self.tableWidget_rabies.horizontalHeaderItem(0)
        item.setText(_translate("rabies_table_window", "Препарат"))
        item = self.tableWidget_rabies.horizontalHeaderItem(1)
        item.setText(_translate("rabies_table_window", "Дата вакцинации"))
        item = self.tableWidget_rabies.horizontalHeaderItem(2)
        item.setText(_translate("rabies_table_window", "Действительно до"))
        item = self.tableWidget_rabies.horizontalHeaderItem(3)
        item.setText(_translate("rabies_table_window", "Номер серии"))
        item = self.tableWidget_rabies.horizontalHeaderItem(4)
        item.setText(_translate("rabies_table_window", "Вет.врач (клиника)"))
        item = self.tableWidget_rabies.horizontalHeaderItem(5)
        item.setText(_translate("rabies_table_window", "id"))
        self.pushButton_exit.setText(_translate("rabies_table_window", "Выйти"))
        self.name_table.setText(_translate("rabies_table_window", "Вакцинация против бешенства"))
        self.pushButton_add.setText(_translate("rabies_table_window", "добавить +"))
        self.pushButton_delete.setText(_translate("rabies_table_window", "удалить -"))
